set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'altercation/vim-colors-solarized'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'rust-lang/rust.vim'	
Plugin 'mattn/emmet-vim'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'scrooloose/nerdtree'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'dhruvasagar/vim-table-mode'
Plugin 'kchmck/vim-coffee-script'
Plugin 'gcmt/taboo.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" Use Space as my leader key.
let mapleader = "\<Space>"

" LeaderMappings
" " .vimrc
nmap <leader>so :source $MYVIMRC<cr>
" " Markdown #TODO: Change to imap!
nmap <leader>dd :r ! date +"\%d.\%m.\%y"<CR>
nmap <leader>[ i<Space><Esc>la<Space>
nmap <leader>] xi*<Space>
nmap <leader>tm :TableModeToggle	

" InsertModeMappings
imap <C-s> <esc>:w<cr>

" Configure Theme 
" syntax enable
" set background=dark
" colorscheme solarized

" autorebalance windows on vim resize
autocmd VimResized * :wincmd =

" Linenumbers
set number! relativenumber
set numberwidth=3

" Whitespace preferences
autocmd Filetype html setlocal ts=2 sw=2 expandtab
autocmd Filetype ruby setlocal ts=2 sw=2 expandtab
autocmd Filetype eruby setlocal ts=2 sw=2 expandtab
autocmd Filetype markdown setlocal ts=2 sw=2 expandtab
